apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-python-7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-python-7 
  name: demo-python-7
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-python-7
    weight: 100 
